[package]
name = "FalkorDB-rs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[features]
falkordb_allocator = []

[dependencies]

[build-dependencies]
cbindgen = "0.26.0"
